database:
  hostName: webapp-database
  image: 
    repository: 484954965141.dkr.ecr.ap-south-1.amazonaws.com/webapp/webapp-database
    tag: "0177ee8"

backend:
  hostName: webapp-backend
  image: 
    repository: 484954965141.dkr.ecr.ap-south-1.amazonaws.com/webapp/webapp-backend
    tag: "0177ee8"

frontend:
  hostName: webapp-frontend
  image: 
    repository: sandipdockerrepo/webapp-frontend
    tag: "latest"
