database:
  hostName: webapp-database
  image: 
    repository: sandipdockerrepo/webapp-database
    tag: "latest"

backend:
  hostName: webapp-backend
  image: 
    repository: sandipdockerrepo/webapp-backend
    tag: "latest"

frontend:
  hostName: webapp-frontend
  image: 
    repository: sandipdockerrepo/webapp-frontend
    tag: "latest"