{{- with .Values.database.persistence }}
{{- if .enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ $.Values.database.hostName }}-pvc"
  {{- if $.Release.Namespace }}
  namespace: {{ $.Release.Namespace }}
  {{- else }}
  namespace: {{ $.Values.commonConfig.namespace }}
  {{- end }}
spec: 
  accessModes:
    - {{ .accessMode }}
  resources:
    requests:
      storage: {{ .size }}
  storageClassName: {{ .storageClass }}
{{- end }}
{{- end }}
