apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.database.hostName }}-dbinit-configmap"
  {{- if .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
  {{- else }}
  namespace: {{ .Values.commonConfig.namespace }}
  {{- end }}
data:
  init.sql: |-
{{ .Files.Get "sql/init.sql" | indent 4 }}
