name: Deploy Workflow

on:
  workflow_call:
    inputs:
      matrix:
        required: true
        type: string
      has-changes:
        required: true
        type: string

    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_REGION:
        required: true
      AWS_ACCOUNT_ID:
        required: true
jobs:
  deploy-changes:
    runs-on: ubuntu-latest
    if: ${{ inputs.has-changes == 'true' }}

    # It allows you to run a single job definition multiple times with different inputs
    # For this case, the entire job will be executed 3 times, each for
    # "webapp_frontend", "webapp_backend" and "webapp_database"
    strategy:
      matrix: ${{ fromJson(inputs.matrix) }}
      # Even if one job fails, all other matrix jobs continue running until completion
      fail-fast: false
    
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v4

      - name: Testing
        run: echo "Testing.."


    # Permissions control what a workflow (or a specific job/step) 
    # can do with the GitHub token (GITHUB_TOKEN) that’s automatically provided during a run
    # Possible values for permission are as follows
    # -------------------------------
    # actions: read|write|none
    # contents: read|write|none
    # pull-requests: read|write|none
    # issues: read|write|none
    # packages: read|write|none
    # deployments: read|write|none
    # checks: read|write|none
    # statuses: read|write|none
    #permissions:
    #  contents: write

    #env:
    #  BUILD_PUSH_PATH: ./infra-ci-scripts/build-and-push-image.sh
    #  UPDATE_HELM_PATH: ./infra-ci-scripts/update-helm-values.sh
    #  COMMIT_HELM_PATH: ./infra-ci-scripts/commit-helm-image-changes.sh
    #steps:
    #  - name: Checkout the source code
    #    uses: actions/checkout@v4

    #  - name: Make the scripts executable
    #    run: |
    #      chmod +x $BUILD_PUSH_PATH
    #      chmod +x $UPDATE_HELM_PATH
    #      chmod +x $COMMIT_HELM_PATH

    #  - name: Configure AWS credentials
    #    uses: aws-actions/configure-aws-credentials@v4
    #    with:
    #      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #      aws-region: ${{ secrets.AWS_REGION }}

    #  - name: Login to AWS ECR
    #    uses: aws-actions/amazon-ecr-login@v2

    #  - name: Build and push images
    #    env:
    #      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
    #      AWS_REGION: ${{ secrets.AWS_REGION }}
    #      GITHUB_SHA: ${{ github.sha }}
    #    run: $BUILD_PUSH_PATH ${{ matrix.services }}

      #- name: Update helm values
      #  run: $UPDATE_HELM_PATH ${{ matrix.services }}

      #- name: Commit helm changes
      #  run: $COMMIT_HELM_PATH ${{ matrix.services }}
