name: Detect Changes Workflow

on: 
  workflow_call:

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    name: Detect changed services
    outputs:
      has-changes: ${{ steps.change-detection.outputs.has-changes }}
      matrix: ${{ steps.change-detection.outputs.matrix }}
      changed-services: ${{ steps.change-detection.outputs.changed-services }}
    env:
      SHELL_SCRIPT_PATH: ./infra-ci-scripts/application-change-detection.sh
    steps:
      - name: Checking out the source code
        uses: actions/chaeckout@v4
        with:
          fetch-depth: 2 # fetching the current and the previous commit to compare for change detection 
      
      - name: Making the script executable
        run: chmod +x $SHELL_SCRIPT_PATH

      - name: Detecting changed services
        id: change-detection
        env:
          GITHUB_EVENT_NAME: ${{ github.event_name }}
        run: $SHELL_SCRIPT_PATH