name: Root Deployment Workflow

on: 
  #push:
  #  branches: [ gitops ]
  #  paths: ['src/**']
  workflow_dispatch:
    
jobs:
  detect-changes:
    uses: ./.github/workflows/detect-changes.yaml

  deploy:
    needs: [detect-changes]
    uses: ./.github/workflows/deploy.yaml

    # Permissions control what a workflow (or a specific job/step) 
    # can do with the GitHub token (GITHUB_TOKEN) that’s automatically provided during a run
    # Possible values for permission are as follows
    # -------------------------------
    # actions: read|write|none
    # contents: read|write|none
    # pull-requests: read|write|none
    # issues: read|write|none
    # packages: read|write|none
    # deployments: read|write|none
    # checks: read|write|none
    # statuses: read|write|none
    permissions:
      contents: write
      
    with:
      matrix: ${{ needs.detect-changes.outputs.matrix }}
      has-changes: ${{ needs.detect-changes.outputs.has-changes }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  #
  #summary:
  #  needs: [detect-changes, deploy]
  #  uses: .github/workflows/summary.yaml