name: Summary Workflow

on:
  workflow_call:
    inputs:
      changed-services:
        required: false
        type: string
      has-changes:
        required: true
        type: string

jobs:
  change-summary:
    runs-on: ubuntu-latest
    env:
      SUMMARY_PATH: ./infra-ci-scripts/summary-generator.sh
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v4

      - name: Make the scripts executable
        run: |
          chmod +x $SUMMARY_PATH

      - name: Create deployment summery
        env:
          GITHUB_SHA: ${{ github.sha }}
          GITHUB_REF_NAME: ${{ github.ref_name }}
          GITHUB_ACTOR: ${{ github.actor }}
        run: $SUMMARY_PATH "${{ inputs.changed-services }}" ${{ inputs.has-changes }}